refactor: latest transactions in portfolio
PayvoHQ/wallet pull request #202
Opened 2021-08-17 07:30 UTC by alesmit

## Summary

https://app.clickup.com/t/1cdm3d3

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-08-17 13:41 UTC, samharperpittam requested changes
@alesmit 

Can we still show a placeholder on the 'Latest Transactions' table on the portfolio page for when no wallets have been added yet please

![image](https://user-images.githubusercontent.com/44671015/129736153-e6306821-66fb-435c-b966-5c3b898636d9.png)

Looks a bit empty atm:
![image](https://user-images.githubusercontent.com/44671015/129736336-a0beb3b6-e062-45e1-bf53-b4181f7bb857.png)

2021-08-17 13:45 UTC, samharperpittam submitted a review, later dismissed
Also it appears the 'Transaction History' header has been changed to 'Latest Transactions' on the Wallet Details page. As the Wallet Details page will show a full history of transactions, i think we should keep the 'Transaction History' header

![image](https://user-images.githubusercontent.com/44671015/129736919-6d60363b-6b8c-4895-baae-977f770cc396.png)

2021-08-18 14:07 UTC, alesmit commented
should be good now

2021-08-19 07:32 UTC, faustbrian approved these changes

2021-08-19 07:33 UTC, merged