feat: implement new voting for Lisk
PayvoHQ/wallet pull request #213
Opened 2021-08-23 05:26 UTC by w3ea

## Summary
https://app.clickup.com/t/1cru3ad

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-08-23 05:41 UTC, faustbrian commented on src/domains/vote/components/DelegateTable/DelegateRow/DelegateRowSkeleton.tsx
> +			{networkName === "LSK" && (
Don't hardcode token or network names. That's against the whole purpose of the SDK and Profiles package.

If there's no way to do what you need to do based on existing data from a `Network` class instance please report it.

2021-08-23 05:43 UTC, faustbrian commented on src/domains/vote/components/DelegateTable/DelegateFooter/DelegateFooter.tsx
> +	const isLiskNetwork = selectedWallet.network().coin() === "LSK";
https://github.com/PayvoHQ/wallet/pull/213/files#r693674277

2021-08-23 05:43 UTC, faustbrian commented on src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.tsx
> +			{networkName === "LSK" && <DelegateVoteAmount rowColor={rowColor} />}
https://github.com/PayvoHQ/wallet/pull/213/files#r693674277

2021-08-23 05:43 UTC, faustbrian commented on src/domains/vote/components/DelegateTable/DelegateTable.helpers.tsx
> +		return [columnName, columnExplorer, coin === "LSK" && columnVoteAmount, columnVote].filter(
https://github.com/PayvoHQ/wallet/pull/213/files#r693674277

2021-08-23 05:44 UTC, faustbrian commented on src/domains/vote/components/DelegateTable/DelegateRow/DelegateRowSkeleton.tsx
> +			{networkName === "LSK" && (
What you are trying to do is probably exposed as `network.requiresStakeAmount()`

2021-08-23 06:03 UTC, w3ea commented on src/domains/vote/components/DelegateTable/DelegateRow/DelegateRowSkeleton.tsx
> +			{networkName === "LSK" && (
yeah you're right, i already used [general phrases](https://github.com/PayvoHQ/wallet/pull/213/files#diff-2402e328181f589554560b02c0f9605724886fbe549893a33b64117e97de0ae6R21)
but didn't notice about `requiresStakeAmount()` method
thanks 👍🏻

2021-08-23 06:58 UTC, faustbrian commented on src/domains/vote/components/DelegateTable/DelegateFooter/DelegateFooter.tsx
> +	const requiresVoteAmount = selectedWallet.network().requiresStakeAmount();
```suggestion
	const requiresStakeAmount = selectedWallet.network().requiresStakeAmount();
```

2021-08-23 07:22 UTC, w3ea commented on src/domains/vote/components/DelegateTable/DelegateFooter/DelegateFooter.tsx
> +	const requiresVoteAmount = selectedWallet.network().requiresStakeAmount();
i thought because we're using [`requiresAmount` ](https://github.com/PayvoHQ/sdk/blob/master/packages/sdk/source/networks/network.models.ts#L114) in SDK, and here we want it only for vote amount column it's ok to use `requiresVoteAmount` :hmhm:
ok i'll change it

2021-08-23 15:14 UTC, alesmit commented on src/domains/vote/components/DelegateTable/DelegateRow/DelegateVoteAmount.tsx
> +								<Input className="flex-1 -mx-4" placeholder="0 LSK" ignoreContext noBorder noShadow />
Maybe we could pass placeholder via props so that if we're required to hardcode at least it's going to be at a higher level in the components tree.

2021-08-23 15:14 UTC, alesmit commented on src/domains/vote/components/DelegateTable/DelegateTable.tsx
> +	const columns = DelegateTableColumns({ isLoading, network: selectedWallet.network() });
This seems to act as a hook, in that case, we could rename it to something like `useDelegateTableColumns`.

2021-08-23 15:17 UTC, alesmit commented on src/tailwind.config.js
> +				91: "22.75rem",
Noticing there's only a tiny difference between values mapped to 88 and 91. Probably worth checking w/design if we can just stick to 88?

2021-08-23 15:27 UTC, w3ea commented on src/domains/vote/components/DelegateTable/DelegateRow/DelegateVoteAmount.tsx
> +								<Input className="flex-1 -mx-4" placeholder="0 LSK" ignoreContext noBorder noShadow />
yeah i want to do the same thing, it's `network.coin()`

2021-08-23 15:31 UTC, w3ea commented on src/domains/vote/components/DelegateTable/DelegateTable.tsx
> +	const columns = DelegateTableColumns({ isLoading, network: selectedWallet.network() });
good point 👌🏻, IDK why i forgot to add `use` to that name

2021-08-23 15:32 UTC, w3ea commented on src/tailwind.config.js
> +				91: "22.75rem",
it's in design
![Screenshot 2021-08-23 195131](https://user-images.githubusercontent.com/24996341/130475027-e2ddeaeb-993a-4b43-b535-f951e716e914.png)

2021-09-01 03:16 UTC, faustbrian commented on src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
> +exports[`VoteList should render with empty list 1`] = `<DocumentFragment />`;
@w3ea is this snapshot correct? Looks wrong but not sure because the title says it should be empty now.

2021-09-01 06:31 UTC, w3ea commented on src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
> +exports[`VoteList should render with empty list 1`] = `<DocumentFragment />`;
yeah that's correct
[previously](https://github.com/PayvoHQ/wallet/blob/develop/src/domains/vote/components/VoteList/VoteList.tsx#L11), it returned the wrapper
but [now](https://github.com/PayvoHQ/wallet/blob/968861279a9c9cfd6bf322abd331e5c0afef2e45/src/domains/vote/components/VoteList/VoteList.tsx#L37) it checks the length of the list

2021-09-10 07:28 UTC, samharperpittam requested changes
We can adjust this tooltip to not include a mention of `%` seeing as it's been removed. 

Can be changed to...

`Number of LSK you want to vote with for a specific delegate`



![image](https://user-images.githubusercontent.com/44671015/132816428-e76b9d76-7e96-46a6-8566-2e82f4ef2c81.png)

2021-09-10 10:53 UTC, samharperpittam approved these changes

2021-09-10 14:20 UTC, merged