Implement i18next translation typing & small refactor
PayvoHQ/wallet pull request #510
Opened 2021-11-02 14:22 UTC by ignromanov

## Summary

- implement i18next translation typing
- update i18next package version
- declare global String functions typing

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-11-02 17:52 UTC, w3ea commented on src/utils/e2e-utils.ts
> -export const lang = (translation: string, values: Record<string, string> = {}): string => {
i think it's better to keep lang function
it's also useful for multiple fields/values
[see slack discussion](https://cryptoarkproject.slack.com/archives/CJFKZSV61/p1629081587234000)

2021-11-03 02:28 UTC, faustbrian commented on src/app/i18n/index.ts
> +	ns: ["translation"],
```suggestion
	ns: [defaultNS],
```

2021-11-03 05:39 UTC, faustbrian requested changes
Looking good but I would keep the `lang` function as it allows for building up translations with nicer DX than manually repeating `replace` calls over and over again depending on the translation string.

2021-11-04 09:44 UTC, faustbrian commented
@ignromanov how's it looking with adding back the `lang` function?

2021-11-04 13:21 UTC, ignromanov commented
> @ignromanov how's it looking with adding back the `lang` function?

got it, there were some typing problems with it
@faustbrian @w3ea now we have `translate()` to use in e2e scripts

2021-11-04 13:35 UTC, faustbrian commented on src/utils/e2e-utils.ts
> +import _ from "lodash";
Avoid adding the whole lodash dependency. Either pull in a specific method since they release each function also as a separate module or use a more lightweight alternative for that specific function like https://github.com/developit/dlv.

2021-11-04 13:43 UTC, ignromanov commented on src/utils/e2e-utils.ts
> +import _ from "lodash";
lodash is a popular library for common things with arrays and objects, it's strange we don't use it yet.
import fixed

2021-11-04 13:46 UTC, faustbrian commented on src/utils/e2e-utils.ts
> +import _ from "lodash";
I know what it is and we removed it from all our projects because it is massively bloated compared to simpler alternatives that achieve the same, even with tree shaking, which we don't really benefit from with electron.

2021-11-04 13:52 UTC, ignromanov commented on src/utils/e2e-utils.ts
> +import _ from "lodash";
Yes, it's a pretty big library, though very functional. 
What alternative could be used with the same extensive object functionality and without installing separate packages for each function?

2021-11-04 13:53 UTC, w3ea commented on src/utils/e2e-utils.ts
> +import _ from "lodash";
and it doesn't use tree shaking (lodash-es does)
https://bundlephobia.com/package/lodash-es@4.17.21
https://bundlephobia.com/package/dlv@1.1.3
it’s a painful package to reduce in file size

like [moment.js](https://momentjs.com/) and [day.js](https://day.js.org/)

2021-11-04 13:55 UTC, faustbrian commented on src/utils/e2e-utils.ts
> +import _ from "lodash";
We pull in specific packages for specific functions if we need them instead of just installing one big library where we'll use a few functions from and a lot of  lodash functions can these days be replaced with simpler implementations in a few lines just by using native functionality.

2021-11-04 15:49 UTC, faustbrian approved these changes

2021-11-04 15:51 UTC, merged