FileSystemPluginService.askUserToSaveFile
PayvoHQ/wallet pull request #558
Opened 2021-11-09 20:57 UTC by Panzenbaby

Resolves [Issue 556](https://github.com/PayvoHQ/wallet/issues/556 )
Resolves [Issue 557](https://github.com/PayvoHQ/wallet/issues/557)

## Summary

Adjust the FileSystemPluginService so that it corresponds to the signature provided by PluginAPI.filesystem. Now a suggested file name can be passed by developers.

I couldn't tell whether a user canceled the dialog or really saved the file. So I avoided treating showSaveDialog cancellation as a success and throw an error instead.

## Checklist
-   [ x ] I checked my changes for obvious issues, debug statements and commented code
-   [ x ] Tests _(if necessary)_
-   [ x ] Ready to be merged

I adjusted one test but the argument doesn't seem to be required. I added it anyway to match the signature and remove the lint error.

2021-11-10 08:04 UTC, Panzenbaby commented
It seems that the action can not checkout my branch to run the checks :(

2021-11-11 01:49 UTC, faustbrian commented on src/plugins/services/filesystem/FileSystemPluginService.ts
> +			throw new Error('Canceled by user');
What's the reason for this having to throw an error instead of returning early?

2021-11-11 01:49 UTC, faustbrian requested changes
Missing tests

2021-11-11 08:10 UTC, Panzenbaby commented on src/plugins/services/filesystem/FileSystemPluginService.ts
> +			throw new Error('Canceled by user');
If you exit this method in the same way in each case, the caller will not be able to determine whether the save was successful or not.
Another solution would be to add a return type like boolean that indicates the success of this operation.

2021-11-11 19:09 UTC, Panzenbaby commented on src/plugins/services/filesystem/FileSystemPluginService.ts
> +			throw new Error('Canceled by user');
I changed the behavior to return a boolean.

2021-11-19 09:12 UTC, Panzenbaby commented
@faustbrian 
There is no button to resolve your requested changes but I added tests. Could you please review again.

2021-11-19 10:39 UTC, goga-m commented
@Panzenbaby is there a particular plugin you are using that needs this change? Can you provide an example so that we could reproduce it in the wallet? 

Thanks in advance

2021-11-19 12:44 UTC, Panzenbaby commented
@goga-m I'm about to rewrite https://github.com/Panzenbaby/ArkStakingRewardReport for the payvo wallet. The plugin offers an export function and I want to display a success or error message if the file was saved or an error occurred. In the event that the user cancels the save dialog, I get the same result as if they had successfully saved the file.

You can check the current behavior by calling
`api.filesystem().askUserToSaveFile('test', 'test').then(() => console.log('I can't tell if the file was saved or if the user abort the dialog')).catch((error) => console.log('An error occurred'));`

Try this once with selecting save and once with cancel. Both leads to the same result.

2021-11-22 03:29 UTC, merged