feat: remove encryption upon registering second signature
PayvoHQ/wallet pull request #559
Opened 2021-11-10 00:33 UTC by dated

## Summary

Closes #505.

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2021-11-11 01:59 UTC, faustbrian submitted a review, later dismissed

2021-11-11 09:41 UTC, samharperpittam requested changes
@dated  - This doesn't appear to be removing the Enc Password after registering a second sig.

Trying to send a transaction after registering a second sig still asks for a Enc Password and results in the following error:

```
{"message":"This wallet does not use PBKDF2 encryption.","type":"Error"}
``

2021-11-11 12:30 UTC, ignromanov commented on src/domains/dashboard/components/Wallets/Wallets.tsx
> +			{modal === "delete" && (
Would be good to implement easy types for the `modal` local state value, like:
`export type WalletModalTypes =  "rename" | "delete";`

2021-11-18 13:38 UTC, faustbrian commented
@dated conflicts

2021-11-19 14:08 UTC, dated commented
> @dated conflicts

done.

2021-11-22 14:55 UTC, samharperpittam approved these changes

2021-11-23 00:23 UTC, merged