style: resolve `testing-library/prefer-explicit-assert` violations
PayvoHQ/wallet pull request #630
Opened 2021-11-25 17:55 UTC by dated

## Summary

See #489.

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [x] Ready to be merged

2021-11-25 22:38 UTC, w3ea commented on src/app/App.test.tsx
> +		await expect(screen.findByText(profileTranslations.PAGE_WELCOME.WITH_PROFILES.TITLE)).resolves.toBeTruthy();
imho `toBeTruthy` on elements does not make any meaningful assertion. [toBeTruthy](https://jestjs.io/docs/expect#tobetruthy) only checks the value after [converting it to boolean](https://github.com/facebook/jest/blob/main/packages/expect/src/matchers.ts#L405). (it's [based on](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_NOT#double_not_!!) the `truthyness` or `falsyness`)
i think it's better to replace them with `toBeVisible` or `toBeInTheDocument`.

[testing-library docs](https://testing-library.com/docs/example-findbytext/) is using `toBeVisible`

> `toBeVisible` checks element from the user's perspective. if an element is accessible by assistive technology, in addition, inaccessible color combinations, opacity, possible occlusion etc.

2021-11-26 00:27 UTC, faustbrian requested changes
See comments

2021-11-26 17:05 UTC, w3ea commented on src/app/components/FilterNetwork/FilterNetwork.test.tsx
>  		userEvent.click(screen.getAllByTestId("FilterNetwork__select-all-checkbox")[0]);
```suggestion
		const selectAllCheckbox = screen.getByTestId("FilterNetwork__select-all-checkbox");

		expect(selectAllCheckbox).toBeVisible();

		userEvent.click(selectAllCheckbox);
		
		// Or in one line
		userEvent.click(screen.getByTestId("FilterNetwork__select-all-checkbox"));
```
according to [this line](https://github.com/PayvoHQ/wallet/pull/630/files#diff-c2a706c56998786118378438c58faf718b6382a6bb479caa9de1714740cd3e46R155), seems to be only one element with this test id, so i think `toBeArray` (& `jest-extended`) is unnecessary here

2021-11-26 18:12 UTC, w3ea approved these changes

2021-11-26 23:59 UTC, merged