fix: show success toast on export profile
PayvoHQ/wallet pull request #833
Opened 2022-01-19 09:24 UTC by w3ea

## Summary

https://github.com/PayvoHQ/wallet/issues/832

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-01-19 09:25 UTC, goga-m approved these changes

2022-01-20 05:14 UTC, anil203 commented
The toast is not showing up for Firefox and Safari.

2022-01-20 05:15 UTC, anil203 requested changes
The toast is not displayed on Firefox and Safari browsers

2022-01-20 05:16 UTC, faustbrian approved these changes

2022-01-20 06:34 UTC, dated approved these changes

2022-01-20 06:46 UTC, merged