refactor: update add participant label
PayvoHQ/wallet pull request #872
Opened 2022-01-25 00:04 UTC by alfonsobries

## Summary

Replaces the "Multisignature Participant" with "Address" when registering multisignature

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-01-25 08:27 UTC, anil203 requested changes
@alfonsobries There seems to be an error here. The change was expected to done to the place holder text. The placeholder text "Select Option" needs to be changed to "Address"
![image](https://user-images.githubusercontent.com/10047242/150939697-06abf654-95d9-4d25-809a-8dd9b76fc4be.png)

2022-01-25 15:07 UTC, alfonsobries commented
my bad @anil203, I updated the recipient select to default the placeholder to "address", should be ok now

2022-01-26 08:59 UTC, anil203 approved these changes

2022-01-26 09:07 UTC, faustbrian approved these changes

2022-01-26 09:12 UTC, faustbrian approved these changes

2022-01-26 09:12 UTC, merged